# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.0b1
_src_path: gh:epics-containers/ioc-template
description: The Simulation AreaDetector generic IOC.
git_platform: github.com
github_org: epics-containers
name: ioc-adsimdetector
repo_uri: git@github.com:epics-containers/ioc-adsimdetector.git
rtems: false
